import React, { useState, useEffect } from 'react';

interface TestimonialProps {
  content: string;
  author: string;
  role: string;
  company: string;
  avatarUrl: string;
}

const testimonials: TestimonialProps[] = [
  {
    content: "ProfileAI transformed my LinkedIn presence. I received 3 interview requests within a week of updating my profile with their AI-generated content.",
    author: "Sarah Johnson",
    role: "Marketing Director",
    company: "TechCorp",
    avatarUrl: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
  },
  {
    content: "As someone who struggles with writing about myself, this tool was a game-changer. It helped me articulate my experience in a way that truly resonates with recruiters.",
    author: "Michael Chen",
    role: "Software Engineer",
    company: "InnovateTech",
    avatarUrl: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
  },
  {
    content: "The profile generated by ProfileAI perfectly balanced professionalism with personality. It helped me stand out in a competitive job market.",
    author: "Emily Rodriguez",
    role: "Product Manager",
    company: "GrowthLabs",
    avatarUrl: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
  }
];

const Testimonial: React.FC<TestimonialProps> = ({ content, author, role, company, avatarUrl }) => {
  return (
    <div className="bg-white rounded-2xl shadow-soft p-6 md:p-8">
      <div className="flex items-center mb-6">
        <div className="flex-shrink-0 mr-4">
          <img
            className="h-12 w-12 rounded-full object-cover"
            src={avatarUrl}
            alt={author}
          />
        </div>
        <div>
          <h4 className="text-lg font-semibold text-gray-900">{author}</h4>
          <p className="text-sm text-gray-600">{role}, {company}</p>
        </div>
      </div>
      <p className="text-gray-700 italic leading-relaxed">"{content}"</p>
    </div>
  );
};

const Testimonials: React.FC = () => {
  const [activeIndex, setActiveIndex] = useState(0);

  // Auto-advance the carousel
  useEffect(() => {
    const interval = setInterval(() => {
      setActiveIndex((current) => (current + 1) % testimonials.length);
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  return (
    <section className="py-20 bg-gradient-to-br from-primary-700 to-primary-900 text-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">What Our Users Say</h2>
          <p className="text-xl text-primary-100 max-w-3xl mx-auto">
            Join thousands of professionals who have transformed their LinkedIn profiles with ProfileAI.
          </p>
        </div>

        <div className="relative max-w-4xl mx-auto">
          <div className="overflow-hidden">
            <div 
              className="flex transition-transform duration-500 ease-in-out"
              style={{ transform: `translateX(-${activeIndex * 100}%)` }}
            >
              {testimonials.map((testimonial, index) => (
                <div key={index} className="w-full flex-shrink-0 px-4">
                  <Testimonial {...testimonial} />
                </div>
              ))}
            </div>
          </div>

          <div className="flex justify-center mt-8">
            {testimonials.map((_, index) => (
              <button
                key={index}
                onClick={() => setActiveIndex(index)}
                className={`w-3 h-3 mx-1 rounded-full transition-all ${
                  activeIndex === index ? 'bg-white' : 'bg-primary-300 opacity-50'
                }`}
                aria-label={`Go to slide ${index + 1}`}
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Testimonials;